### ISSUE TITLE
Circle of Wills

### ISSUE THREAD

**Issue by mcanythingreally** [mcanythingreally/McWoWCata#9]
Set moving mobs inhabittype 1
Swim walking

**Comment by ghost** [comment]
This stops them from doing it.

-- Amera Sky
UPDATE `creature_template` SET `InhabitType` = 1 WHERE (entry = 32745);

-- Shifty Vickers

UPDATE `creature_template` SET `InhabitType` = 1 WHERE (entry = 30137);

**Comment by mcanythingreally** [comment]
Will look into Shifty Vickers more. Still walking over water even after modifying Inhabittype and Movement type. Amera Sky is resolved though

**Comment by mcanythingreally** [comment]
Shifty Vickers is resolved. Ticket closed
